# Generated by Django 3.0.5 on 2020-06-24 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='modifications',
        ),
        migrations.AddField(
            model_name='review',
            name='review',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Recipe'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=250)),
                ('modification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Recipe')),
            ],
        ),
    ]
