# Generated by Django 3.0.5 on 2020-06-24 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200624_0458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modification',
            old_name='modification',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='recipe',
        ),
    ]
